# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './quest_maker/views/character_content_node_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_character_content_node(object):
    def setupUi(self, character_content_node):
        character_content_node.setObjectName("character_content_node")
        character_content_node.resize(315, 625)
        self.verticalLayout = QtWidgets.QVBoxLayout(character_content_node)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box = QtWidgets.QGroupBox(character_content_node)
        self.group_box.setObjectName("group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.h_layout = QtWidgets.QHBoxLayout()
        self.h_layout.setObjectName("h_layout")
        self.move_node_left_bttn = QtWidgets.QPushButton(self.group_box)
        self.move_node_left_bttn.setObjectName("move_node_left_bttn")
        self.h_layout.addWidget(self.move_node_left_bttn)
        self.delete_node_bttn = QtWidgets.QPushButton(self.group_box)
        self.delete_node_bttn.setObjectName("delete_node_bttn")
        self.h_layout.addWidget(self.delete_node_bttn)
        self.move_node_right_bttn = QtWidgets.QPushButton(self.group_box)
        self.move_node_right_bttn.setObjectName("move_node_right_bttn")
        self.h_layout.addWidget(self.move_node_right_bttn)
        self.verticalLayout_2.addLayout(self.h_layout)
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.drops_list = QtWidgets.QListWidget(self.group_box)
        self.drops_list.setMinimumSize(QtCore.QSize(0, 96))
        self.drops_list.setAcceptDrops(True)
        self.drops_list.setAlternatingRowColors(True)
        self.drops_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.drops_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.drops_list.setObjectName("drops_list")
        self.grid_layout.addWidget(self.drops_list, 5, 1, 1, 1)
        self.dialogue = QtWidgets.QTextEdit(self.group_box)
        self.dialogue.setMinimumSize(QtCore.QSize(0, 96))
        self.dialogue.setObjectName("dialogue")
        self.grid_layout.addWidget(self.dialogue, 4, 1, 1, 1)
        self.merchandise_list = QtWidgets.QListWidget(self.group_box)
        self.merchandise_list.setMinimumSize(QtCore.QSize(0, 96))
        self.merchandise_list.setAcceptDrops(True)
        self.merchandise_list.setAlternatingRowColors(True)
        self.merchandise_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.merchandise_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.merchandise_list.setObjectName("merchandise_list")
        self.grid_layout.addWidget(self.merchandise_list, 7, 1, 1, 1)
        self.spells_list = QtWidgets.QListWidget(self.group_box)
        self.spells_list.setMinimumSize(QtCore.QSize(0, 96))
        self.spells_list.setAcceptDrops(True)
        self.spells_list.setAlternatingRowColors(True)
        self.spells_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.spells_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.spells_list.setObjectName("spells_list")
        self.grid_layout.addWidget(self.spells_list, 6, 1, 1, 1)
        self.enemy = QtWidgets.QCheckBox(self.group_box)
        self.enemy.setMaximumSize(QtCore.QSize(16777215, 32))
        self.enemy.setTristate(False)
        self.enemy.setObjectName("enemy")
        self.grid_layout.addWidget(self.enemy, 2, 1, 1, 1)
        self.level = QtWidgets.QSpinBox(self.group_box)
        self.level.setMaximum(10)
        self.level.setObjectName("level")
        self.grid_layout.addWidget(self.level, 1, 1, 1, 1)
        self.level_lbl = QtWidgets.QLabel(self.group_box)
        self.level_lbl.setObjectName("level_lbl")
        self.grid_layout.addWidget(self.level_lbl, 1, 0, 1, 1)
        self.character_list = QtWidgets.QListWidget(self.group_box)
        self.character_list.setMaximumSize(QtCore.QSize(16777215, 32))
        self.character_list.setAcceptDrops(True)
        self.character_list.setAlternatingRowColors(True)
        self.character_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.character_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.character_list.setObjectName("character_list")
        self.grid_layout.addWidget(self.character_list, 0, 1, 1, 1)
        self.dialogue_lbl = QtWidgets.QLabel(self.group_box)
        self.dialogue_lbl.setObjectName("dialogue_lbl")
        self.grid_layout.addWidget(self.dialogue_lbl, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.healer = QtWidgets.QCheckBox(self.group_box)
        self.healer.setObjectName("healer")
        self.horizontalLayout.addWidget(self.healer)
        self.healer_gold_amount = QtWidgets.QSpinBox(self.group_box)
        self.healer_gold_amount.setObjectName("healer_gold_amount")
        self.horizontalLayout.addWidget(self.healer_gold_amount)
        self.grid_layout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.spells_lbl = QtWidgets.QLabel(self.group_box)
        self.spells_lbl.setObjectName("spells_lbl")
        self.grid_layout.addWidget(self.spells_lbl, 6, 0, 1, 1)
        self.drops_lbl = QtWidgets.QLabel(self.group_box)
        self.drops_lbl.setObjectName("drops_lbl")
        self.grid_layout.addWidget(self.drops_lbl, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.group_box)
        self.label_5.setObjectName("label_5")
        self.grid_layout.addWidget(self.label_5, 7, 0, 1, 1)
        self.character_lbl = QtWidgets.QLabel(self.group_box)
        self.character_lbl.setObjectName("character_lbl")
        self.grid_layout.addWidget(self.character_lbl, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.grid_layout)
        self.verticalLayout.addWidget(self.group_box)

        self.retranslateUi(character_content_node)
        QtCore.QMetaObject.connectSlotsByName(character_content_node)

    def retranslateUi(self, character_content_node):
        _translate = QtCore.QCoreApplication.translate
        character_content_node.setWindowTitle(_translate("character_content_node", "character_content_node"))
        self.group_box.setTitle(_translate("character_content_node", "Content Node"))
        self.move_node_left_bttn.setText(_translate("character_content_node", "Move Left"))
        self.delete_node_bttn.setText(_translate("character_content_node", "Delete"))
        self.move_node_right_bttn.setText(_translate("character_content_node", "Move Right"))
        self.dialogue.setPlaceholderText(_translate("character_content_node", "Character Dialogue"))
        self.enemy.setText(_translate("character_content_node", "Enemy"))
        self.level_lbl.setText(_translate("character_content_node", "Level"))
        self.dialogue_lbl.setText(_translate("character_content_node", "Dialogue"))
        self.healer.setText(_translate("character_content_node", "Healer"))
        self.spells_lbl.setText(_translate("character_content_node", "Spells"))
        self.drops_lbl.setText(_translate("character_content_node", "Drops"))
        self.label_5.setText(_translate("character_content_node", "Merchandise"))
        self.character_lbl.setText(_translate("character_content_node", "Character"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    character_content_node = QtWidgets.QWidget()
    ui = Ui_character_content_node()
    ui.setupUi(character_content_node)
    character_content_node.show()
    sys.exit(app.exec_())
