# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_quest_node.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quest_node(object):
    def setupUi(self, quest_node):
        quest_node.setObjectName("quest_node")
        quest_node.resize(250, 800)
        quest_node.setMaximumSize(QtCore.QSize(250, 800))
        quest_node.setAcceptDrops(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(quest_node)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_lbl = QtWidgets.QLabel(quest_node)
        self.name_lbl.setObjectName("name_lbl")
        self.verticalLayout.addWidget(self.name_lbl)
        self.name_entry = QtWidgets.QLineEdit(quest_node)
        self.name_entry.setObjectName("name_entry")
        self.verticalLayout.addWidget(self.name_entry)
        self.giver_lbl = QtWidgets.QLabel(quest_node)
        self.giver_lbl.setObjectName("giver_lbl")
        self.verticalLayout.addWidget(self.giver_lbl)
        self.giver_list = QtWidgets.QListWidget(quest_node)
        self.giver_list.setAcceptDrops(True)
        self.giver_list.setAlternatingRowColors(True)
        self.giver_list.setProperty("isWrapping", False)
        self.giver_list.setObjectName("giver_list")
        self.verticalLayout.addWidget(self.giver_list)
        self.receiver_lbl = QtWidgets.QLabel(quest_node)
        self.receiver_lbl.setObjectName("receiver_lbl")
        self.verticalLayout.addWidget(self.receiver_lbl)
        self.receiver_list = QtWidgets.QListWidget(quest_node)
        self.receiver_list.setAcceptDrops(True)
        self.receiver_list.setAlternatingRowColors(True)
        self.receiver_list.setObjectName("receiver_list")
        self.verticalLayout.addWidget(self.receiver_list)
        self.tabs = QtWidgets.QTabWidget(quest_node)
        self.tabs.setObjectName("tabs")
        self.dialogue_tab = QtWidgets.QWidget()
        self.dialogue_tab.setObjectName("dialogue_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialogue_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.start_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_lbl.setObjectName("start_lbl")
        self.verticalLayout_3.addWidget(self.start_lbl)
        self.start_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.start_entry.setObjectName("start_entry")
        self.verticalLayout_3.addWidget(self.start_entry)
        self.active_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.active_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.active_lbl.setObjectName("active_lbl")
        self.verticalLayout_3.addWidget(self.active_lbl)
        self.active_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.active_entry.setObjectName("active_entry")
        self.verticalLayout_3.addWidget(self.active_entry)
        self.completed_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.completed_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.completed_lbl.setObjectName("completed_lbl")
        self.verticalLayout_3.addWidget(self.completed_lbl)
        self.completed_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.completed_entry.setObjectName("completed_entry")
        self.verticalLayout_3.addWidget(self.completed_entry)
        self.delivered_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.delivered_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.delivered_lbl.setObjectName("delivered_lbl")
        self.verticalLayout_3.addWidget(self.delivered_lbl)
        self.delivered_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.delivered_entry.setObjectName("delivered_entry")
        self.verticalLayout_3.addWidget(self.delivered_entry)
        self.tabs.addTab(self.dialogue_tab, "")
        self.objective_tab = QtWidgets.QWidget()
        self.objective_tab.setObjectName("objective_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.objective_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.add_objective_bttn = QtWidgets.QPushButton(self.objective_tab)
        self.add_objective_bttn.setObjectName("add_objective_bttn")
        self.verticalLayout_4.addWidget(self.add_objective_bttn)
        self.objective_list = QtWidgets.QListWidget(self.objective_tab)
        self.objective_list.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.objective_list.setTabKeyNavigation(True)
        self.objective_list.setDragEnabled(False)
        self.objective_list.setAlternatingRowColors(True)
        self.objective_list.setUniformItemSizes(True)
        self.objective_list.setObjectName("objective_list")
        self.verticalLayout_4.addWidget(self.objective_list)
        self.tabs.addTab(self.objective_tab, "")
        self.verticalLayout.addWidget(self.tabs)

        self.retranslateUi(quest_node)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(quest_node)

    def retranslateUi(self, quest_node):
        _translate = QtCore.QCoreApplication.translate
        quest_node.setWindowTitle(_translate("quest_node", "Form"))
        self.name_lbl.setText(_translate("quest_node", "Quset Name"))
        self.giver_lbl.setText(_translate("quest_node", "Quest Giver"))
        self.receiver_lbl.setText(_translate("quest_node", "Quest Receiver"))
        self.start_lbl.setText(_translate("quest_node", "Quest Start"))
        self.start_entry.setPlaceholderText(_translate("quest_node", "Quest Start"))
        self.active_lbl.setText(_translate("quest_node", "Quest Active"))
        self.active_entry.setPlaceholderText(_translate("quest_node", "Quest Active"))
        self.completed_lbl.setText(_translate("quest_node", "Quest Completed"))
        self.completed_entry.setPlaceholderText(_translate("quest_node", "Quest Completed"))
        self.delivered_lbl.setText(_translate("quest_node", "Quest Delivered"))
        self.delivered_entry.setPlaceholderText(_translate("quest_node", "Quest Delivered"))
        self.tabs.setTabText(self.tabs.indexOf(self.dialogue_tab), _translate("quest_node", "Dialogue"))
        self.add_objective_bttn.setText(_translate("quest_node", "Add Objective"))
        self.tabs.setTabText(self.tabs.indexOf(self.objective_tab), _translate("quest_node", "Objectives"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quest_node = QtWidgets.QWidget()
    ui = Ui_quest_node()
    ui.setupUi(quest_node)
    quest_node.show()
    sys.exit(app.exec_())
