# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './quest_maker/views/quest_node_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quest_node(object):
    def setupUi(self, quest_node):
        quest_node.setObjectName("quest_node")
        quest_node.resize(300, 800)
        quest_node.setMinimumSize(QtCore.QSize(300, 800))
        quest_node.setMaximumSize(QtCore.QSize(302, 2000))
        quest_node.setAcceptDrops(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(quest_node)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box = QtWidgets.QGroupBox(quest_node)
        self.group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.group_box.setObjectName("group_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.move_node_left_bttn = QtWidgets.QPushButton(self.group_box)
        self.move_node_left_bttn.setObjectName("move_node_left_bttn")
        self.horizontalLayout.addWidget(self.move_node_left_bttn)
        self.delete_node_bttn = QtWidgets.QPushButton(self.group_box)
        self.delete_node_bttn.setObjectName("delete_node_bttn")
        self.horizontalLayout.addWidget(self.delete_node_bttn)
        self.move_node_right_bttn = QtWidgets.QPushButton(self.group_box)
        self.move_node_right_bttn.setObjectName("move_node_right_bttn")
        self.horizontalLayout.addWidget(self.move_node_right_bttn)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.name_lbl = QtWidgets.QLabel(self.group_box)
        self.name_lbl.setObjectName("name_lbl")
        self.verticalLayout_6.addWidget(self.name_lbl)
        self.name_entry = QtWidgets.QLineEdit(self.group_box)
        self.name_entry.setObjectName("name_entry")
        self.verticalLayout_6.addWidget(self.name_entry)
        self.giver_lbl = QtWidgets.QLabel(self.group_box)
        self.giver_lbl.setObjectName("giver_lbl")
        self.verticalLayout_6.addWidget(self.giver_lbl)
        self.giver_list = QtWidgets.QListWidget(self.group_box)
        self.giver_list.setMaximumSize(QtCore.QSize(16777215, 32))
        self.giver_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.giver_list.setAcceptDrops(True)
        self.giver_list.setAlternatingRowColors(True)
        self.giver_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.giver_list.setProperty("isWrapping", False)
        self.giver_list.setObjectName("giver_list")
        self.verticalLayout_6.addWidget(self.giver_list)
        self.receiver_lbl = QtWidgets.QLabel(self.group_box)
        self.receiver_lbl.setObjectName("receiver_lbl")
        self.verticalLayout_6.addWidget(self.receiver_lbl)
        self.receiver_list = QtWidgets.QListWidget(self.group_box)
        self.receiver_list.setMaximumSize(QtCore.QSize(16777215, 32))
        self.receiver_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.receiver_list.setAcceptDrops(True)
        self.receiver_list.setAlternatingRowColors(True)
        self.receiver_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.receiver_list.setObjectName("receiver_list")
        self.verticalLayout_6.addWidget(self.receiver_list)
        self.tabs = QtWidgets.QTabWidget(self.group_box)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setObjectName("tabs")
        self.dialogue_tab = QtWidgets.QWidget()
        self.dialogue_tab.setObjectName("dialogue_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialogue_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.person_speaking = QtWidgets.QTabWidget(self.dialogue_tab)
        self.person_speaking.setObjectName("person_speaking")
        self.quest_giver = QtWidgets.QWidget()
        self.quest_giver.setObjectName("quest_giver")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.quest_giver)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.g_start_lbl = QtWidgets.QLabel(self.quest_giver)
        self.g_start_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.g_start_lbl.setObjectName("g_start_lbl")
        self.verticalLayout_2.addWidget(self.g_start_lbl)
        self.g_start_entry = QtWidgets.QTextEdit(self.quest_giver)
        self.g_start_entry.setObjectName("g_start_entry")
        self.verticalLayout_2.addWidget(self.g_start_entry)
        self.g_active_lbl = QtWidgets.QLabel(self.quest_giver)
        self.g_active_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.g_active_lbl.setObjectName("g_active_lbl")
        self.verticalLayout_2.addWidget(self.g_active_lbl)
        self.g_active_entry = QtWidgets.QTextEdit(self.quest_giver)
        self.g_active_entry.setObjectName("g_active_entry")
        self.verticalLayout_2.addWidget(self.g_active_entry)
        self.g_completed_lbl = QtWidgets.QLabel(self.quest_giver)
        self.g_completed_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.g_completed_lbl.setObjectName("g_completed_lbl")
        self.verticalLayout_2.addWidget(self.g_completed_lbl)
        self.g_completed_entry = QtWidgets.QTextEdit(self.quest_giver)
        self.g_completed_entry.setObjectName("g_completed_entry")
        self.verticalLayout_2.addWidget(self.g_completed_entry)
        self.g_delivered_lbl = QtWidgets.QLabel(self.quest_giver)
        self.g_delivered_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.g_delivered_lbl.setObjectName("g_delivered_lbl")
        self.verticalLayout_2.addWidget(self.g_delivered_lbl)
        self.g_delivered_entry = QtWidgets.QTextEdit(self.quest_giver)
        self.g_delivered_entry.setObjectName("g_delivered_entry")
        self.verticalLayout_2.addWidget(self.g_delivered_entry)
        self.person_speaking.addTab(self.quest_giver, "")
        self.quest_receiver = QtWidgets.QWidget()
        self.quest_receiver.setObjectName("quest_receiver")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.quest_receiver)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.r_start_lbl = QtWidgets.QLabel(self.quest_receiver)
        self.r_start_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.r_start_lbl.setObjectName("r_start_lbl")
        self.verticalLayout_5.addWidget(self.r_start_lbl)
        self.r_start_entry = QtWidgets.QTextEdit(self.quest_receiver)
        self.r_start_entry.setObjectName("r_start_entry")
        self.verticalLayout_5.addWidget(self.r_start_entry)
        self.r_active_lbl = QtWidgets.QLabel(self.quest_receiver)
        self.r_active_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.r_active_lbl.setObjectName("r_active_lbl")
        self.verticalLayout_5.addWidget(self.r_active_lbl)
        self.r_active_entry = QtWidgets.QTextEdit(self.quest_receiver)
        self.r_active_entry.setObjectName("r_active_entry")
        self.verticalLayout_5.addWidget(self.r_active_entry)
        self.r_completed_lbl = QtWidgets.QLabel(self.quest_receiver)
        self.r_completed_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.r_completed_lbl.setObjectName("r_completed_lbl")
        self.verticalLayout_5.addWidget(self.r_completed_lbl)
        self.r_completed_entry = QtWidgets.QTextEdit(self.quest_receiver)
        self.r_completed_entry.setObjectName("r_completed_entry")
        self.verticalLayout_5.addWidget(self.r_completed_entry)
        self.r_delivered_lbl = QtWidgets.QLabel(self.quest_receiver)
        self.r_delivered_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.r_delivered_lbl.setObjectName("r_delivered_lbl")
        self.verticalLayout_5.addWidget(self.r_delivered_lbl)
        self.r_delivered_entry = QtWidgets.QTextEdit(self.quest_receiver)
        self.r_delivered_entry.setObjectName("r_delivered_entry")
        self.verticalLayout_5.addWidget(self.r_delivered_entry)
        self.person_speaking.addTab(self.quest_receiver, "")
        self.verticalLayout_3.addWidget(self.person_speaking)
        self.tabs.addTab(self.dialogue_tab, "")
        self.objective_tab = QtWidgets.QWidget()
        self.objective_tab.setObjectName("objective_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.objective_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.objective_list = QtWidgets.QListWidget(self.objective_tab)
        self.objective_list.setAcceptDrops(True)
        self.objective_list.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.objective_list.setTabKeyNavigation(True)
        self.objective_list.setDragEnabled(False)
        self.objective_list.setAlternatingRowColors(True)
        self.objective_list.setUniformItemSizes(True)
        self.objective_list.setObjectName("objective_list")
        self.verticalLayout_4.addWidget(self.objective_list)
        self.tabs.addTab(self.objective_tab, "")
        self.verticalLayout_6.addWidget(self.tabs)
        self.verticalLayout.addWidget(self.group_box)

        self.retranslateUi(quest_node)
        self.tabs.setCurrentIndex(0)
        self.person_speaking.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(quest_node)

    def retranslateUi(self, quest_node):
        _translate = QtCore.QCoreApplication.translate
        quest_node.setWindowTitle(_translate("quest_node", "Quest Node"))
        self.group_box.setTitle(_translate("quest_node", "Quest Node"))
        self.move_node_left_bttn.setText(_translate("quest_node", "Move Left"))
        self.delete_node_bttn.setText(_translate("quest_node", "Delete"))
        self.move_node_right_bttn.setText(_translate("quest_node", "Move Right"))
        self.name_lbl.setText(_translate("quest_node", "Quset Name"))
        self.giver_lbl.setText(_translate("quest_node", "Quest Giver"))
        self.giver_list.setToolTip(_translate("quest_node", "Drag and drop characters from world object database."))
        self.receiver_lbl.setText(_translate("quest_node", "Quest Receiver"))
        self.receiver_list.setToolTip(_translate("quest_node", "Drag and drop characters from world object database."))
        self.g_start_lbl.setText(_translate("quest_node", "Ques Giver Start"))
        self.g_start_entry.setPlaceholderText(_translate("quest_node", "Quest Giver Start"))
        self.g_active_lbl.setText(_translate("quest_node", "Quest Giver Active"))
        self.g_active_entry.setPlaceholderText(_translate("quest_node", "Quest Giver Active"))
        self.g_completed_lbl.setText(_translate("quest_node", "Quest Giver Completed"))
        self.g_completed_entry.setPlaceholderText(_translate("quest_node", "Quest Giver Completed"))
        self.g_delivered_lbl.setText(_translate("quest_node", "Quest Giver Delivered"))
        self.g_delivered_entry.setPlaceholderText(_translate("quest_node", "Quest Giver Delivered"))
        self.person_speaking.setTabText(self.person_speaking.indexOf(self.quest_giver), _translate("quest_node", "Quest Giver"))
        self.r_start_lbl.setText(_translate("quest_node", "Quest Receiver Start"))
        self.r_start_entry.setPlaceholderText(_translate("quest_node", "Quest Receiver Start"))
        self.r_active_lbl.setText(_translate("quest_node", "Quest Receiver Active"))
        self.r_active_entry.setPlaceholderText(_translate("quest_node", "Quest Receiver Active"))
        self.r_completed_lbl.setText(_translate("quest_node", "Quest Receiver Completed"))
        self.r_completed_entry.setPlaceholderText(_translate("quest_node", "Quest Receiver Completed"))
        self.r_delivered_lbl.setText(_translate("quest_node", "Quest Receiver Delivered"))
        self.r_delivered_entry.setPlaceholderText(_translate("quest_node", "Quest Receiver Delivered"))
        self.person_speaking.setTabText(self.person_speaking.indexOf(self.quest_receiver), _translate("quest_node", "Quest Receiver"))
        self.tabs.setTabText(self.tabs.indexOf(self.dialogue_tab), _translate("quest_node", "Dialogue"))
        self.objective_list.setToolTip(_translate("quest_node", "Drag and drop from world object database."))
        self.tabs.setTabText(self.tabs.indexOf(self.objective_tab), _translate("quest_node", "Objectives"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quest_node = QtWidgets.QWidget()
    ui = Ui_quest_node()
    ui.setupUi(quest_node)
    quest_node.show()
    sys.exit(app.exec_())
