# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './quest_maker/views/quest_node_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quest_node(object):
    def setupUi(self, quest_node):
        quest_node.setObjectName("quest_node")
        quest_node.resize(320, 1000)
        quest_node.setMaximumSize(QtCore.QSize(320, 1000))
        quest_node.setAcceptDrops(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(quest_node)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box = QtWidgets.QGroupBox(quest_node)
        self.group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.group_box.setObjectName("group_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.move_node_left_bttn = QtWidgets.QPushButton(self.group_box)
        self.move_node_left_bttn.setObjectName("move_node_left_bttn")
        self.button_layout.addWidget(self.move_node_left_bttn)
        self.delete_node_bttn = QtWidgets.QPushButton(self.group_box)
        self.delete_node_bttn.setObjectName("delete_node_bttn")
        self.button_layout.addWidget(self.delete_node_bttn)
        self.move_node_right_bttn = QtWidgets.QPushButton(self.group_box)
        self.move_node_right_bttn.setObjectName("move_node_right_bttn")
        self.button_layout.addWidget(self.move_node_right_bttn)
        self.verticalLayout_6.addLayout(self.button_layout)
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.label = QtWidgets.QLabel(self.group_box)
        self.label.setObjectName("label")
        self.grid_layout.addWidget(self.label, 3, 0, 1, 1)
        self.giver_list = QtWidgets.QListWidget(self.group_box)
        self.giver_list.setMaximumSize(QtCore.QSize(16777215, 32))
        self.giver_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.giver_list.setAcceptDrops(True)
        self.giver_list.setAlternatingRowColors(True)
        self.giver_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.giver_list.setProperty("isWrapping", False)
        self.giver_list.setObjectName("giver_list")
        self.grid_layout.addWidget(self.giver_list, 5, 1, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.group_box)
        self.name_lbl.setObjectName("name_lbl")
        self.grid_layout.addWidget(self.name_lbl, 2, 0, 1, 1)
        self.completer_lbl = QtWidgets.QLabel(self.group_box)
        self.completer_lbl.setObjectName("completer_lbl")
        self.grid_layout.addWidget(self.completer_lbl, 7, 0, 1, 1)
        self.completer_list = QtWidgets.QListWidget(self.group_box)
        self.completer_list.setMinimumSize(QtCore.QSize(0, 0))
        self.completer_list.setMaximumSize(QtCore.QSize(16777215, 32))
        self.completer_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.completer_list.setAcceptDrops(True)
        self.completer_list.setAlternatingRowColors(True)
        self.completer_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.completer_list.setObjectName("completer_list")
        self.grid_layout.addWidget(self.completer_list, 7, 1, 1, 1)
        self.giver_lbl = QtWidgets.QLabel(self.group_box)
        self.giver_lbl.setObjectName("giver_lbl")
        self.grid_layout.addWidget(self.giver_lbl, 5, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.group_box)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 64))
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setObjectName("listWidget")
        self.grid_layout.addWidget(self.listWidget, 3, 1, 1, 1)
        self.name_entry = QtWidgets.QLineEdit(self.group_box)
        self.name_entry.setMinimumSize(QtCore.QSize(0, 32))
        self.name_entry.setMaximumSize(QtCore.QSize(16777215, 32))
        self.name_entry.setObjectName("name_entry")
        self.grid_layout.addWidget(self.name_entry, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.grid_layout)
        self.tabs = QtWidgets.QTabWidget(self.group_box)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setObjectName("tabs")
        self.dialogue_tab = QtWidgets.QWidget()
        self.dialogue_tab.setObjectName("dialogue_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialogue_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.start_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_lbl.setObjectName("start_lbl")
        self.verticalLayout_3.addWidget(self.start_lbl)
        self.start_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.start_entry.setObjectName("start_entry")
        self.verticalLayout_3.addWidget(self.start_entry)
        self.active_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.active_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.active_lbl.setObjectName("active_lbl")
        self.verticalLayout_3.addWidget(self.active_lbl)
        self.active_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.active_entry.setObjectName("active_entry")
        self.verticalLayout_3.addWidget(self.active_entry)
        self.completed_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.completed_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.completed_lbl.setObjectName("completed_lbl")
        self.verticalLayout_3.addWidget(self.completed_lbl)
        self.completed_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.completed_entry.setObjectName("completed_entry")
        self.verticalLayout_3.addWidget(self.completed_entry)
        self.delivered_lbl = QtWidgets.QLabel(self.dialogue_tab)
        self.delivered_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.delivered_lbl.setObjectName("delivered_lbl")
        self.verticalLayout_3.addWidget(self.delivered_lbl)
        self.delivered_entry = QtWidgets.QTextEdit(self.dialogue_tab)
        self.delivered_entry.setObjectName("delivered_entry")
        self.verticalLayout_3.addWidget(self.delivered_entry)
        self.tabs.addTab(self.dialogue_tab, "")
        self.objective_tab = QtWidgets.QWidget()
        self.objective_tab.setObjectName("objective_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.objective_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.objective_list = QtWidgets.QListWidget(self.objective_tab)
        self.objective_list.setAcceptDrops(True)
        self.objective_list.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.objective_list.setTabKeyNavigation(True)
        self.objective_list.setDragEnabled(False)
        self.objective_list.setAlternatingRowColors(True)
        self.objective_list.setUniformItemSizes(True)
        self.objective_list.setObjectName("objective_list")
        self.verticalLayout_4.addWidget(self.objective_list)
        self.tabs.addTab(self.objective_tab, "")
        self.verticalLayout_6.addWidget(self.tabs)
        self.verticalLayout.addWidget(self.group_box)

        self.retranslateUi(quest_node)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(quest_node)

    def retranslateUi(self, quest_node):
        _translate = QtCore.QCoreApplication.translate
        quest_node.setWindowTitle(_translate("quest_node", "Quest Node"))
        self.group_box.setTitle(_translate("quest_node", "Quest Node"))
        self.move_node_left_bttn.setText(_translate("quest_node", "Move Left"))
        self.delete_node_bttn.setText(_translate("quest_node", "Delete"))
        self.move_node_right_bttn.setText(_translate("quest_node", "Move Right"))
        self.label.setText(_translate("quest_node", "Next Quest"))
        self.giver_list.setToolTip(_translate("quest_node", "Drag and drop characters from world object database."))
        self.name_lbl.setText(_translate("quest_node", "Quset Name"))
        self.completer_lbl.setText(_translate("quest_node", "Quest Completer"))
        self.completer_list.setToolTip(_translate("quest_node", "Drag and drop characters from world object database."))
        self.giver_lbl.setText(_translate("quest_node", "Quest Giver"))
        self.start_lbl.setText(_translate("quest_node", "Quest Start"))
        self.start_entry.setPlaceholderText(_translate("quest_node", "Quest Start"))
        self.active_lbl.setText(_translate("quest_node", "Quest Active"))
        self.active_entry.setPlaceholderText(_translate("quest_node", "Quest Active"))
        self.completed_lbl.setText(_translate("quest_node", "Quest Completed"))
        self.completed_entry.setPlaceholderText(_translate("quest_node", "Quest Completed"))
        self.delivered_lbl.setText(_translate("quest_node", "Quest Delivered"))
        self.delivered_entry.setPlaceholderText(_translate("quest_node", "Quest Delivered"))
        self.tabs.setTabText(self.tabs.indexOf(self.dialogue_tab), _translate("quest_node", "Dialogue"))
        self.objective_list.setToolTip(_translate("quest_node", "Drag and drop from world object database."))
        self.tabs.setTabText(self.tabs.indexOf(self.objective_tab), _translate("quest_node", "Objectives"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quest_node = QtWidgets.QWidget()
    ui = Ui_quest_node()
    ui.setupUi(quest_node)
    quest_node.show()
    sys.exit(app.exec_())
